# Web Scraping for Used Car Prices from Autotrader.ca

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Importing required modules
from splinter import Browser
from splinter.exceptions import ElementDoesNotExist
from bs4 import BeautifulSoup
import requests
import re
import pymongo
import pandas as pd
from sqlalchemy import create_engine,inspect, func
import numpy as np
import time
#from config import api_key

In [13]:
# This is to initialize Splinter for Windows users
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [14]:
# list to store extracted values

title_list=[]
year_list=[]
price_list=[]
loc_list=[]
date_list=[]
milage_list=[]
car_list=[]
model_list=[]
trans_list=[]

# loop to scrap website

url = "https://www.autotrader.ca/cars/?rcp=15&rcs=0&srt=9&prx=-1&hprc=True&wcp=True&sts=New-Used&inMarket=advancedSearch"
browser.visit(url)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')
results = soup.find_all('div', class_='newSRPDesign')


i=1

while i<=2:
  
    for result in results:
       
        
        try:
            
            # scrape the price
            price = result.find('span', class_='price-amount').text
            price_list.append(price)
            # scrape the  Title
            ctitle = result.find('div', class_='listing-details').h2.a.span.text
            #words=['lease', 'take over', 'finance', 'financing', 'leasing', 'takeover', 'financed', 'leased', 'transfer', 'transferring']
            #for word in words:
            
                #if word in result.find('div', class_='title').text.split():
                    #print('a listing including lease or finance was removed')
                #elif word in result.find('div', class_='description').text.split():
                    #print('a listing including lease or finance was removed')
                #else:
            btitle= ctitle.split('\n')[1].replace('                                    ','')
            title = btitle.split('                                    ')[0]
            year = title.split(" ")[0]
            cartype= title.split(" ")[1]
            model = title.split(" ")[2]
            title_list.append(title)
            year_list.append(year)
            car_list.append(cartype)
            model_list.append(model)
         
            
            
        # scrape the  Location
            #location = result.find('div', class_='location').text.split()[0]
            #loc_list.append(location)
        
         
        
        
        
        # scrape the  Date
            #date = result.find('span', class_='date-posted').text
            #date_list.append(date)
        # scrape the  details
            details = result.find('div', class_='kms').text#.split('"')[0]         
            milage=details
           
            
            milage_list.append(milage)            
   
    
        except AttributeError:
            date=''
        except IndexError:
            cartype=''
            model=''
    
    browser.find_link_by_text(1+i).first.click()
    i=i+1    
# store the extracted valuse in dictionary            
Dict={}
Dict["Title"]=title_list
Dict["Car Type"]=car_list
Dict["Model"]=model_list
Dict["Price"]=price_list
#Dict["Location"]=loc_list
#Dict["Date"]=date_list
Dict["Milage"]=milage_list
Dict["Year"]=year_list
#Dict["Transmission"]=trans_list

In [16]:
df=pd.DataFrame.from_dict(Dict, orient='index')
df=df.transpose()
df

,Title,Car Type,Model,Price,Milage,Year
0,2020 Nissan Murano PLATINUM,Nissan,Murano,"$44,613","\nMileage 36,447 km\n ...",2020
1,2017 Lexus RX 350 Executive Pkg- Panoramic Roo...,Lexus,RX,"$37,900","\nMileage 162,300 km\n ...",2017
2,2011 BMW 328 X-DRIVE 6 VITESSE MANUEL CUIR TOI...,BMW,328,"$6,994","\nMileage 81,736 km\n ...",2011
3,"2015 Mazda Mazda3 GS W/SUNROOF, LOW KMS, AUTO,...",Mazda,Mazda3,"$12,988","\nMileage 9,058 km\n ...",2015
4,2019 Volkswagen Atlas COMFORTLINE,Volkswagen,Atlas,"$47,749","\nMileage 41,105 km\n ...",2019
5,2019 Toyota Corolla XSE: Sunroof/ Navigation/ ...,Toyota,Corolla,"$21,900","\nMileage 124,000 km\n ...",2019
6,2011 Audi A3 TDI Premium,Audi,A3,"$10,995","\nMileage 8,310 km\n ...",2011
7,2019 BMW i8 Coupe,BMW,i8,"$102,900","\nMileage 42,132 km\n ...",2019
8,2019 Dodge Grand Caravan CANADA VALUE PKG*REAR...,Dodge,Grand,"$20,844","\nMileage 60,243 km\n ...",2019
9,2018 Hyundai Tucson 2.0L SE AWD,Hyundai,Tucson,"$26,888","\nMileage 83,787 km\n ...",2018
10,2013 Audi ALLROAD QUATTRO Premium,Audi,ALLROAD,"$18,995","\nMileage 49,170 km\n ...",2013
11,"2018 Chevrolet Impala LT - V6, Alloys, Moonroo...",Chevrolet,Impala,"$17,927","\nMileage 119,000 km\n ...",2018
12,2016 Honda Odyssey 4dr Wgn EX,Honda,Odyssey,"$21,000","\nMileage 46,400 km\n ...",2016
13,2016 Volkswagen Jetta TRENDLINE + BACK UP CAME...,Volkswagen,Jetta,"$11,995","\nMileage 52,415 km\n ...",2016
14,2015 Nissan Rogue SV AWD (4X4) TECH +MAGS+TOIT...,Nissan,Rogue,"$18,496","\nMileage 17,881 km\n ...",2015
15,2018 Hyundai Tucson +CAMERA+SIEGE CHAUFF+,Hyundai,Tucson,"$20,686","\nMileage 34,217 km\n ...",2018
16,2016 Nissan Sentra SV +CAMERA+AILERON+,Nissan,Sentra,"$11,995","\nMileage 29,326 km\n ...",2016
17,2019 Nissan Kicks SV +MAGS+CAMERA+,Nissan,Kicks,"$20,495","\nMileage 21,732 km\n ...",2019
18,2019 Nissan Kicks SV +MAGS+CAMERA+,Nissan,Kicks,"$20,495","\nMileage 119,200 km\n ...",2019
19,2011 Nissan Rogue SV AWD +MAGS+CAMERA+,Nissan,Rogue,"$9,495","\nMileage 74,403 km\n ...",2011
20,2016 Nissan Micra SR +MAGS+CAMERA+,Nissan,Micra,"$9,472","\nMileage 43,576 km\n ...",2016
21,2017 Nissan Sentra SR TURBO 6MT +MAGS+SIEGE CH...,Nissan,Sentra,"$13,444","\nMileage 41,743 km\n ...",2017
22,2017 Nissan Sentra SR TURBO 6MT +GPS+TOIT+MAGS+,Nissan,Sentra,"$15,495","\nMileage 29,669 km\n ...",2017
23,2017 Nissan Sentra SV DELUXE +GPS+TOIT+MAGS+,Nissan,Sentra,"$14,495","\nMileage 33,742 km\n ...",2017
24,2017 Nissan Rogue S AWD (4X4) +AWD+CAMERA+SIEG...,Nissan,Rogue,"$17,722","\nMileage 40,094 km\n ...",2017
25,2017 Nissan Rogue SV AWD (4X4) +MAGS+CAMERA+D...,Nissan,Rogue,"$19,597","\nMileage 38,857 km\n ...",2017
26,2015 Nissan Micra SV +BAS KILO+GROUPE ELEC+,Nissan,Micra,"$8,861","\nMileage 36,447 km\n ...",2015
27,2020 Nissan Murano PLATINUM,Nissan,Murano,"$44,613","\nMileage 162,300 km\n ...",2020
28,2017 Lexus RX 350 Executive Pkg- Panoramic Roo...,Lexus,RX,"$37,900","\nMileage 81,736 km\n ...",2017
29,2011 BMW 328 X-DRIVE 6 VITESSE MANUEL CUIR TOI...,BMW,328,"$6,994","\nMileage 9,058 km\n ...",2011
30,"2015 Mazda Mazda3 GS W/SUNROOF, LOW KMS, AUTO,...",Mazda,Mazda3,"$12,988","\nMileage 41,105 km\n ...",2015
31,2019 Volkswagen Atlas COMFORTLINE,Volkswagen,Atlas,"$47,749","\nMileage 124,000 km\n ...",2019
32,2019 Toyota Corolla XSE: Sunroof/ Navigation/ ...,Toyota,Corolla,"$21,900","\nMileage 8,310 km\n ...",2019
33,2011 Audi A3 TDI Premium,Audi,A3,"$10,995","\nMileage 42,132 km\n ...",2011
34,2019 BMW i8 Coupe,BMW,i8,"$102,900","\nMileage 60,243 km\n ...",2019
35,2019 Dodge Grand Caravan CANADA VALUE PKG*REAR...,Dodge,Grand,"$20,844","\nMileage 83,787 km\n ...",2019
36,2018 Hyundai Tucson 2.0L SE AWD,Hyundai,Tucson,"$26,888","\nMileage 49,170 km\n ...",2018
37,2013 Audi ALLROAD QUATTRO Premium,Audi,ALLROAD,"$18,995","\nMileage 119,000 km\n ...",2013
38,"2018 Chevrolet Impala LT - V6, Alloys, Moonroo...",Chevrolet,Impala,"$17,927","\nMileage 46,400 km\n ...",2018
39,2016 Honda Odyssey 4dr Wgn EX,Honda,Odyssey,"$21,000","\nMileage 52,415 km\n ...",2016
40,2016 Volkswagen Jetta TRENDLINE + BACK UP CAME...,Volkswagen,Jetta,"$11,995","\nMileage 17,881 km\n ...",2016
41,2015 Nissan Rogue SV AWD (4X4) TECH +MAGS+TOIT...,Nissan,Rogue,"$18,496","\nMileage 34,217 km\n ...",2015
42,2018 Hyundai Tucson +CAMERA+SIEGE CHAUFF+,Hyundai,Tucson,"$20,686","\nMileage 29,326 km\n ...",2018
43,2016 Nissan Sentra SV +CAMERA+AILERON+,Nissan,Sentra,"$11,995","\nMileage 21,732 km\n ...",2016
44,2019 Nissan Kicks SV +MAGS+CAMERA+,Nissan,Kicks,"$20,495","\nMileage 119,200 km\n ...",2019
45,2019 Nissan Kicks SV +MAGS+CAMERA+,Nissan,Kicks,"$20,495","\nMileage 74,403 km\n ...",2019
46,2011 Nissan Rogue SV AWD +MAGS+CAMERA+,Nissan,Rogue,"$9,495","\nMileage 43,576 km\n ...",2011
47,2016 Nissan Micra SR +MAGS+CAMERA+,Nissan,Micra,"$9,472","\nMileage 41,743 km\n ...",2016
48,2017 Nissan Sentra SR TURBO 6MT +MAGS+SIEGE CH...,Nissan,Sentra,"$13,444","\nMileage 29,669 km\n ...",2017
49,2017 Nissan Sentra SR TURBO 6MT +GPS+TOIT+MAGS+,Nissan,Sentra,"$15,495","\nMileage 33,742 km\n ...",2017
50,2017 Nissan Sentra SV DELUXE +GPS+TOIT+MAGS+,Nissan,Sentra,"$14,495","\nMileage 40,094 km\n ...",2017
51,2017 Nissan Rogue S AWD (4X4) +AWD+CAMERA+SIEG...,Nissan,Rogue,"$17,722","\nMileage 38,857 km\n ...",2017
52,2017 Nissan Rogue SV AWD (4X4) +MAGS+CAMERA+D...,Nissan,Rogue,"$19,597",None,2017
53,2015 Nissan Micra SV +BAS KILO+GROUPE ELEC+,Nissan,Micra,"$8,861",None,2015

In [29]:
df['Title'].value_counts()

2018 Toyota Prius v GAS SAVING HYBRID-EDITION 5 PASSENGER 1.8L - DOHC.    4
2017 Ram 2500 Mega Cab Limited                                            2
2016 Honda Civic lx                                                       2
2016 Audi A4 Komfort plus                                                 2
2012 Chevrolet Corvette Grand Sport                                       2
1974 Ford Bronco                                                          2
2020 Chevrolet Suburban LT  - Leather Seats - Luxury Package              2
2019 Honda Fit AUTOMATIQUE                                                2
2001 Ford Escape 4dr 103  WB XLS 4WD                                      2
2017 Ford F-150 4WD SuperCrew 145 XLT                                     2
2018 BMW 3 Series 330i xDrive M-SPORT *NAVI/CAMERA/ROOF/RED INT/LED       2
2008 Ford Focus 2dr Cpe SES                                               2
2018 Dodge Journey SXT  - Low Mileage                                     2
1974 Jaguar XKE                                                           2
1968 Plymouth GTX 400                                                     2
2013 Ford F-150 4WD SuperCab 145 FX4                                      2
2006 Infiniti M35 LOADED/ 2 YEARS WARRANTY/LOW KMS                        2
2011 Nissan SENTRA SE-R SE-R                                              2
2008 Hyundai Accent 3dr HB Auto GL                                        2
2014 Dodge Journey FWD 4dr Canada Value Pkg                               2
2012 Ford F-150 4WD SuperCab 145  FX4                                     2
2012 Fiat 500 2dr HB Pop                                                  2
2016 Ford F-150 90 Days Deferral|4WD|XLT                                  2
2011 MINI Cooper Clubman 2dr Cpe S                                        2
2006 Toyota Tundra Access Cab 128 V8 4WD                                  2
2004 Hyundai Santa Fe 4dr SUV GLS AWD 2.7L Auto                           2
2012 Honda Civic 4dr Auto EX                                              2
2008 Chevrolet 2500 LT                                                    2
2020 Chevrolet Corvette C8 Stingray 3LT                                   2
2017 Hyundai Sonata **GL**NO ACCIDENT**LOW KM**ONE OWNER**REAR CAMERA*    2
                                                                         ..
2016 Chrysler 200 Limited,$105b/w,Heated seats/Steering Wheel,Remote      2
2020 Lincoln Corsair Ultra                                                2
2019 Mazda CX-3 GS Auto AWD                                               2
2016 Subaru Forester Touring PanaRoof Htd Seat Backcam Pwr Liftgate       2
2015 Ram 3500 LARAMIE BLACK APPEARANCE CREW CAB DIESEL                    2
2018 Jeep Grand Cherokee Limited 4x4                                      2
1993 Land Rover Defender 110                                              2
2015 Ram 3500 LARAMIE CREW CAB SWB 4WD 6.7L LARAMIE                       2
2016 Ford F-150 4WD SuperCrew 157  Lariat                                 2
2011 Toyota Tundra 4WD Double Cab 165 5.7L SR5                            2
2015 Hyundai Veloster 3dr Cpe Auto Turbo                                  2
2017 Honda CR-V AWD 5dr LX                                                2
2019 Jaguar F-Pace 25t R-Sport AWD PANO ROOF / NAVIGATION / REAR CAM      2
2014 Hyundai Elantra 4dr Sdn Auto Limited w/Navi                          2
2005 Kia Sportage 4dr EX 4WD V6 Auto                                      2
2009 Volkswagen City Jetta 4dr Sdn Man                                    2
2019 Jeep Wrangler UNLIMITED JL 4X4 CUSTOM WHEEL PKG ONLY 22K             2
1969 Chevrolet Camaro SS                                                  2
2017 Lexus RX 350 AWD 4dr                                                 2
2011 Toyota Camry 4dr Sdn I4 Auto LE                                      2
2011 Acura MDX AWD 4dr                                                    2
2017 Kia Sorento EX V6 AWD + 7 PLACES + GARANTIE + MAGS +                 2
2020 Mercedes-Benz GLC300 4MATIC SUV                                      2
2007 Toyota Sienna 5dr XLE Mobility 8-Passenger 2WD                       2
2020 Ram 1500 Longhorn                                                    2
2016 Ford Expedition PLATINUM 4WD DVD MOON LOADED 2ND ROW CAPTAINS        2
2016 BMW 4-Series 435i xDrive                                             2
1974 Chevrolet Nova                                                       2
2014 Jeep Wrangler 4WD 2dr Sport                                          2
2011 Dodge RAM 3500 PICKUP Slt                                            2
Name: Title, Length: 111, dtype: int64

In [ ]:
df["Price"] = df["Price"].str.replace("$", "")
df["Price"] = df["Price"].str.replace(",", "")
df["Milage"] = df["Milage"].str.replace(",", "")
df["Milage"] = df["Milage"].str.replace("\nMileage", "")
df["Milage"] = df["Milage"].str.replace("\n", "")
df["Milage"] = df["Milage"].str.replace("km", "")

In [ ]:
df.reset_index()
df.dropna()
df.drop_duplicates()
df = df.mask(df.eq('None')).dropna()

In [ ]:
df

In [ ]:
df['Milage'].value_count()

In [ ]:
from config import password
connection_string = "postgres:"+password+"@localhost:5432/hondadb"
engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# Confirm tables
#engine.table_names()
inspector = inspect(engine)
inspector.get_table_names()

In [ ]:
inspector.get_columns("cardb")

In [ ]:
df.to_sql(name='cardb', con=engine, if_exists='replace', index=True)

In [ ]:
sql_DF = pd.read_sql("SELECT * FROM cardb",
                     con=engine)

In [ ]:
sql_DF.info()