# Web Scraping for Used Car Prices from Autotrader.ca

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [50]:
# Importing required modules
from splinter import Browser
from splinter.exceptions import ElementDoesNotExist
from bs4 import BeautifulSoup
import requests
import re
import pymongo
import pandas as pd
from sqlalchemy import create_engine,inspect, func
import numpy as np
import time
import sqlite3
#from config import api_key

In [37]:
# This is to initialize Splinter for Windows users
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [38]:
# list to store extracted values

title_list=[]
year_list=[]
price_list=[]
loc_list=[]
date_list=[]
milage_list=[]
car_list=[]
model_list=[]
trans_list=[]

# loop to scrap website
#scraping 600 pages with 100 listings per pge
for item_num in range(0, 60001, 100):
    url = "https://www.autotrader.ca/cars/?rcp=100&rcs="+str(item_num)+"&srt=9&prx=-1&hprc=True&wcp=True&sts=New-Used&inMarket=advancedSearch"
    browser.visit(url)
    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    results = soup.find_all('div', class_='newSRPDesign')


    for result in results:
               
        try:
                
            # scrape the price
            price = result.find('span', class_='price-amount').text
            price_list.append(price)
            # scrape the  Title
            ctitle = result.find('div', class_='listing-details').h2.a.span.text
            
                
            btitle= ctitle.split('\n')[1].replace('                                    ','')
            title = btitle.split('                                    ')[0]
            year = title.split(" ")[0]
            cartype= title.split(" ")[1]
            model = title.split(" ")[2]
            title_list.append(title)
            year_list.append(year)
            car_list.append(cartype)
            model_list.append(model)
         
            
            
        # scrape the  Location
            location = result.find('span', class_='proximity-text').text.split()[1]
            loc_list.append(location)
            
            
            
            
            
        #scrape the milage
            details = result.find('div', class_='kms').text#.split('"')[0]         
            milage=details
            milage_list.append(milage)            
   
    
        except AttributeError:
            date=''
        except IndexError:
            cartype=''
            model=''
            
#browser.find_link_by_text(i+1).first.click()
#i=i+1


# store the extracted valuse in dictionary            
Dict={}
Dict["Title"]=title_list
Dict["Car Type"]=car_list
Dict["Model"]=model_list
Dict["Price"]=price_list
Dict["Location"]=loc_list
#Dict["Date"]=date_list
Dict["Milage"]=milage_list
Dict["Year"]=year_list
#Dict["Transmission"]=trans_list

In [86]:
df=pd.DataFrame.from_dict(Dict, orient='index')
df=df.transpose()
ndf=df.drop_duplicates(['Title', 'Price', 'Year'])
ndf

,Title,Car Type,Model,Price,Location,Milage,Year
0,2018 Ford F-150,Ford,F-150,"$33,888","Langley,","\nMileage 64,965 km\n ...",2018
1,2017 Mercedes-Benz GLS GLS 450,Mercedes-Benz,GLS,"$54,887","Toronto,","\nMileage 57,449 km\n ...",2017
2,2016 Dodge Journey AWD 4dr R-T / Leather / Blu...,Dodge,Journey,"$18,888","Calgary,","\nMileage 28,567 km\n ...",2016
3,"2017 Ford Edge SPORT, TOIT PANO, CUIR, GPS/NAV",Ford,Edge,"$30,995","Vancouver,","\nMileage 63,500 km\n ...",2017
4,"2019 Nissan Versa Note SV - just like new, ver...",Nissan,Versa,"$18,988","Scarborough,","\nMileage 87,760 km\n ...",2019
5,2016 Volkswagen Golf R GOLF - TECHNOLOGY PACKA...,Volkswagen,Golf,"$33,995","Toronto,",\nMileage 419 km\n ...,2016
6,2014 Jeep Grand Cherokee Overland *LOCALLY DRI...,Jeep,Grand,"$25,688","St-Esprit,","\nMileage 237,366 km\n ...",2014
7,2015 GMC Acadia FWD 4dr SLE1,GMC,Acadia,"$16,998","Guelph,","\nMileage 42,420 km\n ...",2015
8,2019 Ram 1500 Classic Express Night | 4x4 | Cr...,Ram,1500,"$42,390","Bridgewater,","\nMileage 27,766 km\n ...",2019
9,2020 Jeep Compass Limited,Jeep,Compass,"$40,665","Toronto,","\nMileage 120,750 km\n ...",2020
10,2015 Nissan Micra NO PAYMENTS FOR 3 MONTHS! !!!,Nissan,Micra,"$10,777",Grande,"\nMileage 21,432 km\n ...",2015
11,2017 Volkswagen Golf 5dr HB Auto 1.8 TSI Trend...,Volkswagen,Golf,"$18,888",Sherwood,"\nMileage 67,252 km\n ...",2017
12,"2019 Jeep Grand Cherokee Limited AWD, Navi, Su...",Jeep,Grand,"$38,995","Candiac,","\nMileage 136,000 km\n ...",2019
13,2017 Chevrolet Cruze LT,Chevrolet,Cruze,"$14,998","Candiac,","\nMileage 132,000 km\n ...",2017
14,"2019 Jeep Grand Cherokee Limited AWD, Navi, Su...",Jeep,Grand,"$38,795","Candiac,","\nMileage 108,042 km\n ...",2019
15,2015 Toyota Corolla 4dr Sdn CVT S,Toyota,Corolla,"$12,950","Candiac,","\nMileage 79,344 km\n ...",2015
16,"2019 Jeep Grand Cherokee Limited 4x4, Navi, Su...",Jeep,Grand,"$38,895","Candiac,","\nMileage 109,200 km\n ...",2019
17,2018 Mazda Mazda3 GX A/C BLUETOOTH,Mazda,Mazda3,"$13,999","Candiac,","\nMileage 228,816 km\n ...",2018
18,2018 Toyota Camry XSE V6,Toyota,Camry,"$28,609","Moncton,","\nMileage 28,848 km\n ...",2018
19,2017 Nissan 370Z,Nissan,370Z,"$33,500","Moncton,","\nMileage 10,334 km\n ...",2017
20,2016 BMW 5 Series,BMW,5,"$27,500","Moncton,","\nMileage 36,300 km\n ...",2016
21,2007 Toyota Corolla 4dr Sdn Auto CE,Toyota,Corolla,"$3,700","Moncton,","\nMileage 28,500 km\n ...",2007
22,2008 Ford Escape 4WD 4dr V6 XLT,Ford,Escape,"$5,800","Moncton,","\nMileage 315,550 km\n ...",2008
23,2012 Dodge Journey AWD 4dr R/T,Dodge,Journey,"$9,500","Moncton,","\nMileage 68,479 km\n ...",2012
24,2008 Ford Escape 4WD 4dr V6 XLT,Ford,Escape,"$5,500","Moncton,","\nMileage 90,751 km\n ...",2008
25,2017 Cadillac XT5 Haut de gamme Luxe AWD Navig...,Cadillac,XT5,"$31,995","Moncton,","\nMileage 60,365 km\n ...",2017
26,2012 Jeep Grand Cherokee 4WD 4dr Overland,Jeep,Grand,"$15,995",Port,"\nMileage 69,054 km\n ...",2012
27,2020 Hyundai Tucson Preferred,Hyundai,Tucson,"$33,729","Surrey,","\nMileage 74,358 km\n ...",2020
29,2017 Ram 1500,Ram,1500,"$36,975","Surrey,","\nMileage 39,767 km\n ...",2017
30,2014 Dodge Grand Caravan 30th Anniversary,Dodge,Grand,"$12,797","Surrey,","\nMileage 230,000 km\n ...",2014
...,...,...,...,...,...,...,...
67281,2016 Chevrolet Cruze LT AIR CLIMATISÉ - Caméra...,Chevrolet,Cruze,"$10,794",None,None,2016
67282,2014 Nissan Sentra S Vitres Électriques - Port...,Nissan,Sentra,"$6,994",None,None,2014
67283,2018 Honda Civic *ACHAT EN LIGNE*LIVRAISON SAN...,Honda,Civic,"$19,382",None,None,2018
67284,2016 Honda CR-V *ACHAT EN LIGNE*LIVRAISON SANS...,Honda,CR-V,"$19,728",None,None,2016
67285,2016 Honda CR-V *ACHAT EN LIGNE*LIVRAISON SANS...,Honda,CR-V,"$19,738",None,None,2016
67286,2016 Honda Civic *ACHAT EN LIGNE*LIVRAISON SAN...,Honda,Civic,"$14,994",None,None,2016
67287,2016 Honda Civic *ACHAT EN LIGNE*LIVRAISON SAN...,Honda,Civic,"$15,457",None,None,2016
67288,2015 Honda Civic *ACHAT EN LIGNE*LIVRAISON SAN...,Honda,Civic,"$10,368",None,None,2015
67289,2017 Honda Civic *ACHAT EN LIGNE*LIVRAISON SAN...,Honda,Civic,"$16,324",None,None,2017
67290,2016 Nissan Rogue SV **AWD**,Nissan,Rogue,"$17,777",None,None,2016
67291,2018 Hyundai Elantra GL AUTO BAS KILO,Hyundai,Elantra,"$15,666",None,None,2018
67292,2017 Honda CR-V LX FWD,Honda,CR-V,"$22,888",None,None,2017
67293,2017 Nissan Rogue BLUETOOTH BACKUP CAMERA NO A...,Nissan,Rogue,"$18,500",None,None,2017
67294,2013 Kia Sorento EX V6 AWD DEFLETEURS VITRES C...,Kia,Sorento,"$9,994",None,None,2013
67295,2005 Honda Civic DX PAS CHER,Honda,Civic,"$1,497",None,None,2005
67296,2016 Subaru Legacy 3.6R w/Limited & Tech Pkg,Subaru,Legacy,"$19,995",None,None,2016
67297,2017 Subaru Crosstrek Sport,Subaru,Crosstrek,"$20,995",None,None,2017
67298,2014 Chevrolet Corvette Z51,Chevrolet,Corvette,"$55,000",None,None,2014
67299,2004 Dodge Ram 1500 SLT 4.7L V8 AC AUTOMATIQUE,Dodge,Ram,"$2,495",None,None,2004
67301,2003 Hyundai Accent 4dr Sdn GL Auto,Hyundai,Accent,"$1,500",None,None,2003
67302,2015 Toyota Sienna LE,Toyota,Sienna,"$22,994",None,None,2015
67303,"2015 Chrysler 200 C AWD,INT CUIR, TOIT PANORAM...",Chrysler,200,"$14,948",None,None,2015
67304,2020 Jeep Compass Sport,Jeep,Compass,"$33,380",None,None,2020
67305,2020 Jeep Compass Trailhawk,Jeep,Compass,"$38,275",None,None,2020
67306,2020 Ram 1500 Rebel,Ram,1500,"$67,380",None,None,2020
67307,2020 Ram 1500 Big Horn,Ram,1500,"$52,245",None,None,2020
67308,"2019 Ram ProMaster City ST CAMÉRA RECUL, BLUET...",Ram,ProMaster,"$24,948",None,None,2019
67309,2017 Mazda CX-3 GX - GPS - CAMÉRA - BLUETOOTH,Mazda,CX-3,"$15,657",None,None,2017
67310,2016 Hyundai Accent GL - CRUISE - BLUETOOTH - ...,Hyundai,Accent,"$9,877",None,None,2016
67311,2017 Mazda CX-9 GS AWD - CAMÉRA - SIÈGES CHAUF...,Mazda,CX-9,"$25,777",None,None,2017

In [87]:
ndf["Milage"] = ndf["Milage"].str.replace("\nMileage", "")
ndf["Milage"] = ndf["Milage"].str.replace("\n", "")
ndf["Milage"] = ndf["Milage"].str.replace("km", "")
ndf["Milage"] = ndf["Milage"].str.replace('                                 ', "")
ndf["Milage"] = ndf["Milage"].str.replace(' ', "")
ndf["Milage"] = ndf["Milage"].str.replace(",", "")
ndf["Price"] = ndf["Price"].str.replace("$", "")
ndf["Price"] = ndf["Price"].str.replace(",", "")
ndf["Location"] = ndf["Location"].str.replace(",", "")

In [88]:
ndf.reset_index()
ndf.dropna()
ndf.drop_duplicates()
ndf = ndf.mask(ndf.eq('None')).dropna()

In [89]:
ndf

,Title,Car Type,Model,Price,Location,Milage,Year
0,2018 Ford F-150,Ford,F-150,33888,Langley,64965,2018
1,2017 Mercedes-Benz GLS GLS 450,Mercedes-Benz,GLS,54887,Toronto,57449,2017
2,2016 Dodge Journey AWD 4dr R-T / Leather / Blu...,Dodge,Journey,18888,Calgary,28567,2016
3,"2017 Ford Edge SPORT, TOIT PANO, CUIR, GPS/NAV",Ford,Edge,30995,Vancouver,63500,2017
4,"2019 Nissan Versa Note SV - just like new, ver...",Nissan,Versa,18988,Scarborough,87760,2019
5,2016 Volkswagen Golf R GOLF - TECHNOLOGY PACKA...,Volkswagen,Golf,33995,Toronto,419,2016
6,2014 Jeep Grand Cherokee Overland *LOCALLY DRI...,Jeep,Grand,25688,St-Esprit,237366,2014
7,2015 GMC Acadia FWD 4dr SLE1,GMC,Acadia,16998,Guelph,42420,2015
8,2019 Ram 1500 Classic Express Night | 4x4 | Cr...,Ram,1500,42390,Bridgewater,27766,2019
9,2020 Jeep Compass Limited,Jeep,Compass,40665,Toronto,120750,2020
10,2015 Nissan Micra NO PAYMENTS FOR 3 MONTHS! !!!,Nissan,Micra,10777,Grande,21432,2015
11,2017 Volkswagen Golf 5dr HB Auto 1.8 TSI Trend...,Volkswagen,Golf,18888,Sherwood,67252,2017
12,"2019 Jeep Grand Cherokee Limited AWD, Navi, Su...",Jeep,Grand,38995,Candiac,136000,2019
13,2017 Chevrolet Cruze LT,Chevrolet,Cruze,14998,Candiac,132000,2017
14,"2019 Jeep Grand Cherokee Limited AWD, Navi, Su...",Jeep,Grand,38795,Candiac,108042,2019
15,2015 Toyota Corolla 4dr Sdn CVT S,Toyota,Corolla,12950,Candiac,79344,2015
16,"2019 Jeep Grand Cherokee Limited 4x4, Navi, Su...",Jeep,Grand,38895,Candiac,109200,2019
17,2018 Mazda Mazda3 GX A/C BLUETOOTH,Mazda,Mazda3,13999,Candiac,228816,2018
18,2018 Toyota Camry XSE V6,Toyota,Camry,28609,Moncton,28848,2018
19,2017 Nissan 370Z,Nissan,370Z,33500,Moncton,10334,2017
20,2016 BMW 5 Series,BMW,5,27500,Moncton,36300,2016
21,2007 Toyota Corolla 4dr Sdn Auto CE,Toyota,Corolla,3700,Moncton,28500,2007
22,2008 Ford Escape 4WD 4dr V6 XLT,Ford,Escape,5800,Moncton,315550,2008
23,2012 Dodge Journey AWD 4dr R/T,Dodge,Journey,9500,Moncton,68479,2012
24,2008 Ford Escape 4WD 4dr V6 XLT,Ford,Escape,5500,Moncton,90751,2008
25,2017 Cadillac XT5 Haut de gamme Luxe AWD Navig...,Cadillac,XT5,31995,Moncton,60365,2017
26,2012 Jeep Grand Cherokee 4WD 4dr Overland,Jeep,Grand,15995,Port,69054,2012
27,2020 Hyundai Tucson Preferred,Hyundai,Tucson,33729,Surrey,74358,2020
29,2017 Ram 1500,Ram,1500,36975,Surrey,39767,2017
30,2014 Dodge Grand Caravan 30th Anniversary,Dodge,Grand,12797,Surrey,230000,2014
...,...,...,...,...,...,...,...
46588,2020 Hyundai Elantra Sport DCT,Hyundai,Elantra,29009,Ottawa,75194,2020
46590,2020 Hyundai Venue Ultimate w-Black Interior IVT,Hyundai,Venue,26909,Ottawa,58900,2020
46592,2017 MINI Convertible Cooper,MINI,Convertible,22995,Ottawa,121975,2017
46593,2018 Land Rover Range Rover Sport HSE | WE SLA...,Land,Rover,75524,Edmonton,17195,2018
46594,2016 Kia Sedona LX+ Heated Seats ! Power doors...,Kia,Sedona,15497,Edmonton,119471,2016
46595,2018 Audi A4 quattro,Audi,A4,28625,Edmonton,52400,2018
46598,2016 Subaru Forester 2.5i LIMITED | NAVI | EYE...,Subaru,Forester,20950,Rosetown,89071,2016
46599,2018 Nissan Qashqai SL AWD CVT CLEAN HISTORY O...,Nissan,Qashqai,21798,Prince,152000,2018
46600,2013 Hyundai Sonata SE cuir toit ouvrant mags ...,Hyundai,Sonata,9992,Exeter,163142,2013
46601,2015 Mercedes-Benz CLA-Class CLA250 4MATIC AMG...,Mercedes-Benz,CLA-Class,23995,Sherbrooke,33085,2015
46602,2012 Volkswagen Jetta 2.0 TDI Comfortline REDU...,Volkswagen,Jetta,9999,Vernon,60670,2012
46603,2019 Ram 1500 Laramie,Ram,1500,50151,Orangeville,68657,2019
46604,2020 Hyundai Kona 2.0L Preferred AWD,Hyundai,Kona,26609,Toronto,80785,2020
46607,2020 Hyundai Kona 2.0L Luxury AWD,Hyundai,Kona,29559,Vernon,84500,2020
46608,2019 Ford F-150 Raptor 4WD SuperCrew 5.5' Box,Ford,F-150,78449,Vernon,100567,2019
46611,2020 Jeep Grand Cherokee Altitude,Jeep,Grand,57880,Vernon,72441,2020
46615,2020 Ram 1500 Classic Express,Ram,1500,56300,Delson,36325,2020
46616,2020 Jeep Grand Cherokee Altitude,Jeep,Grand,57605,Delson,22365,2020
46617,2020 GMC Sierra 1500 4WD Crew Cab 147 Denali,GMC,Sierra,64848,Delson,23729,2020
46618,2020 GMC Sierra 1500 4WD Crew Cab 147,GMC,Sierra,41507,Delson,33007,2020
46619,2020 Chevrolet SILVERADO 2500HD 4WD Reg Cab 14...,Chevrolet,SILVERADO,61132,Ottawa,48475,2020
46620,2020 Chevrolet Equinox AWD 4dr LT w-1LT,Chevrolet,Equinox,35353,Ottawa,147205,2020
46623,2020 Chevrolet Colorado WT,Chevrolet,Colorado,36809,Woodstock,38000,2020
46624,2020 Chevrolet Malibu LT,Chevrolet,Malibu,30273,Richmond,35000,2020
46625,2020 Chevrolet Blazer RS,Chevrolet,Blazer,55573,Calgary,222417,2020
46626,2020 Chevrolet Colorado 4WD ZR2,Chevrolet,Colorado,59563,Vancouver,66078,2020
46627,2020 Chevrolet Equinox LT,Chevrolet,Equinox,41697,Vancouver,99135,2020
46628,2020 GMC SIERRA 2500HD Denali,GMC,SIERRA,89712,Toronto,70855,2020
46629,2020 Chevrolet Equinox LT,Chevrolet,Equinox,41297,Etobicoke,73745,2020
46633,2020 Honda Pilot Touring 7-Passenger,Honda,Pilot,56031,Kingston,92948,2020

In [90]:
from config import password
connection_string = "postgres:"+password+"@localhost:5432/hondadb"
engine = create_engine(f'postgresql://{connection_string}')

In [91]:
# Confirm tables
#engine.table_names()
inspector = inspect(engine)
inspector.get_table_names()

['cleanedhondadb2', 'cleanedcardb', 'cleanedcardb2', 'cardb', 'hondadb']

In [92]:
inspector.get_columns("cardb")

[{'name': 'index',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Title',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Car Type',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Model',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Price',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Location',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Milage',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None},
 {'name': 'Year',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'autoincrement': False,
  'comment': None}]

In [93]:
ndf.to_sql(name='cardb', con=engine, if_exists='replace', index=True)

In [94]:
sql_DF = pd.read_sql("SELECT * FROM cardb",
                     con=engine)

In [95]:
sql_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40993 entries, 0 to 40992
Data columns (total 8 columns):
index       40993 non-null int64
Title       40993 non-null object
Car Type    40993 non-null object
Model       40993 non-null object
Price       40993 non-null object
Location    40993 non-null object
Milage      40993 non-null object
Year        40993 non-null object
dtypes: int64(1), object(7)
memory usage: 2.5+ MB

In [96]:
conn = sqlite3.connect('car.sqlite')
ndf.to_sql('carsdb', conn, if_exists='replace', index=False)

In [97]:
sql_DF2=pd.read_sql('select * from carsdb', conn)

In [98]:
sql_DF2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40993 entries, 0 to 40992
Data columns (total 7 columns):
Title       40993 non-null object
Car Type    40993 non-null object
Model       40993 non-null object
Price       40993 non-null object
Location    40993 non-null object
Milage      40993 non-null object
Year        40993 non-null object
dtypes: object(7)
memory usage: 2.2+ MB